#pragma once
#define TICK_RATE 60
#define FRAME_RATE 30
#define Tetris_Width 20
#define Tetris_Height 20
#define SCORE_WIDTH 6
#define HIT_THE_FLOOR_COOLDOWN FRAME_RATE * 2
#define SLIDE_DOWN_COOLDOWN FRAME_RATE * 0.2
#define HIT_OTHER_PIECE_FLOOR_COOLDOWN FRAME_RATE * 1
#define GAME_OVER_ANIMATION_COOLDOWN FRAME_RATE / 10